name: clarity_app
description: "思考・感情記録アプリ - プライバシーファースト設計"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ローカルデータベース
  sqflite: ^2.4.0
  path: ^1.9.1
  
  # 設定・状態管理
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  
  # セキュリティ
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6
  
  # UI・アニメーション
  material_design_icons_flutter: ^7.0.7296
  fl_chart: ^0.69.2
  lottie: 3.3.1
  
  # HTTP・API
  http: ^1.3.2
  dio: ^5.7.0
  
  # 日付・時刻
  intl: ^0.19.0
  
  # ファイル操作
  path_provider: ^2.1.5
  file_picker: ^8.1.4
  
  # UUID生成
  uuid: ^4.5.1
  
  # JSON処理（Notion連携用）
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # JSON処理（Notion連携用）
  json_serializable: ^6.8.0
  build_runner: ^2.4.7

flutter:
  # Material Design icons
  uses-material-design: true

  # アセット設定
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # フォント設定（将来追加予定）
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic